cursor #ede0d4
cursor_text_color #d3c4b4

foreground            #ede0d4
background            #18120c
selection_foreground  #3e2d16
selection_background  #dec2a2
url_color             #f6bc70

color0   #18120c
color1   #e2497d
color2   #96d66e
color3   #dbae7b
color4   #b47624
color5   #b89568
color6   #f6bc70
color7   #abb2bf
color8   #5c6370
color9   #e05f8e
color10  #a8e086
color11  #e8c297
color12  #ffcb8c
color13  #ac6941
color14  #90763e
color15  #ffffff
