# Core Services & Bar
exec-once = waybar -c ~/.config/hypr/waybar/config.jsonc -s ~/.config/hypr/waybar/style.css
exec-once = hyprpaper
exec-once = systemctl --user start hyprpolkitagent
exec-once = gnome-keyring-daemon --start --components=secrets

# Clipboard Management
exec-once = wl-clip-persist --clipboard regular --reconnect-tries 0
exec-once = wl-paste --type text --watch cliphist store

# Desktop Environment Utilities
exec-once = swaync
exec-once = swayosd-server
exec-once = swayosd-libinput-backend --exclude-caps-lock

# Wallpaper (Uncomment if you want to use swaybg)
# exec-once = swaybg -i ~/Pictures/Wallpaper/arch.jpg

# Startup Notification
exec-once = sleep 1 && notify-send "System" "Startup complete!"
